interface Listing {
    PROP_TYPE: string,
    LIST_NO: string,
    LIST_AGENT: string,
    LIST_OFFICE: string,
    STATUS: string,
    LIST_PRICE: string,
    STREET_NO: string,
    STREET_NAME: string,
    UNIT_NO: string,
    TOWN_NUM: string,
    AREA: string,
    ZIP_CODE: string,
    LENDER_OWNED: string,
    REMARKS: string,
    PHOTO_COUNT: string,
    PHOTO_DATE: string,
    PHOTO_MASK: string,
    COUNTY: string,
    STATE: string,
    RN_TYPE: string,
    NO_ROOMS: string,
    NO_BEDROOMS: string,
    NO_FULL_BATHS: string,
    NO_HALF_BATHS: string,
    MASTER_BATH: string,
    PARKING_SPACES: string,
    LOT_SIZE: string,
    SQUARE_FEET: string
}

export default Listing